### ISSUE TITLE
`nocompatible` in neovim

### ISSUE THREAD

**Issue by chriserin** [dkarter/dotfiles#11]
https://github.com/dkarter/dotfiles/blob/438a2ff6312329d1e5cf01f87f0bfd2d6644ecea/config/nvim/lua/core/options.lua#L10-L11

In the `:h compatible` 

> 'cp' 'nocompatible' 'nocp' 'compatible' (Nvim is always "nocompatible".)

**Comment by dkarter** [comment]
Nice! thanks Chris! :)
