### ISSUE TITLE
How did you configure your airline in NeoVim part 1

### ISSUE THREAD

**Issue by carlevison** [dkarter/dotfiles#5]
How did you configure your airline with the blocks? like this.

![airline](https://i.imgur.com/A4T3ymm.png)

Thanks.

**Comment by dkarter** [comment]
See https://github.com/dkarter/dotfiles/blob/9dffc485d01cfea3869b1650ddf87f9c2d6ed2f3/vimrc#L314

You would need a patched NerdFont https://github.com/ryanoasis/nerd-fonts

I am using https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode - so make sure you download the font, install it on your system and then use it in your terminal emulator
